"""
Script để gộp các file SQL quan trọng thành file one-shot.sql
Thứ tự: create-all-tables.sql -> sample-data.sql -> questions-and-quiz.sql -> jobs_data_insertion.sql
"""

import os
from pathlib import Path

# Đường dẫn tương đối
SCRIPT_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent
SQL_DIR = PROJECT_ROOT / "sql"
OUTPUT_FILE = SQL_DIR / "one-shot.sql"

# Danh sách file SQL cần gộp theo thứ tự
SQL_FILES = [
    "create-all-tables.sql",
    "sample-data.sql",
    "questions-and-quiz.sql",
    "jobs_data_insertion.sql"
]

def read_sql_file(file_path):
    """Đọc nội dung file SQL"""
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        return content
    except Exception as e:
        print(f"❌ Lỗi khi đọc file {file_path}: {e}")
        return None

def merge_sql_files():
    """Gộp các file SQL thành một file duy nhất"""
    print("🔄 Bắt đầu gộp các file SQL...")
    print(f"📁 Thư mục SQL: {SQL_DIR}")
    print(f"📝 File output: {OUTPUT_FILE}")
    print("-" * 60)
    
    merged_content = []
    
    # Header cho file output
    merged_content.append("-- =========================================")
    merged_content.append("-- ONE-SHOT SQL DEPLOYMENT SCRIPT")
    merged_content.append("-- Auto-generated by merge_all_sql.py")
    merged_content.append("-- =========================================")
    merged_content.append("")
    
    # Gộp từng file
    for sql_file in SQL_FILES:
        file_path = SQL_DIR / sql_file
        
        if not file_path.exists():
            print(f"⚠️  File không tồn tại: {sql_file}")
            continue
        
        print(f"✅ Đọc file: {sql_file}")
        content = read_sql_file(file_path)
        
        if content:
            # Thêm separator và tên file
            merged_content.append(f"\n-- =========================================")
            merged_content.append(f"-- SOURCE: {sql_file}")
            merged_content.append(f"-- =========================================\n")
            merged_content.append(content)
            merged_content.append("\n")
    
    # Ghi ra file output
    try:
        with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
            f.write('\n'.join(merged_content))
        
        print("-" * 60)
        print(f"✅ Đã tạo file {OUTPUT_FILE.name} thành công!")
        print(f"📊 Tổng kích thước: {OUTPUT_FILE.stat().st_size:,} bytes")
        
    except Exception as e:
        print(f"❌ Lỗi khi ghi file output: {e}")
        return False
    
    return True

if __name__ == "__main__":
    print("\n" + "=" * 60)
    print("  MERGE SQL FILES - PAC WEBSITE DEPLOYMENT")
    print("=" * 60 + "\n")
    
    success = merge_sql_files()
    
    print("\n" + "=" * 60)
    if success:
        print("  ✅ HOÀN TẤT!")
    else:
        print("  ❌ CÓ LỖI XẢY RA!")
    print("=" * 60 + "\n")
